version: '2'

networks:
  gonet:
    driver: bridge

services:

  api:
    build: api
    image: wf/go-api
    container_name: ${APP_NAME:?err}-api
    secrets:
      - pg-secret
    depends_on:
      - db
    networks: 
      - gonet
  
  db:
    image: postgres
    container_name: ${APP_NAME:?err}-db
    ports: 
      - 5432:5432
    restart: always
    secrets:
      - pg-secret
    volumes: 
      - ./data/pg:/var/lib/postgresql/data
    environment: 
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=pgdemodb
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg-secret
    networks: 
      - gonet
    
  proxy:
    image: nginx:alpine
    container_name: ${APP_NAME:?err}-proxy
    ports:
      - 80:80
    depends_on: 
      - api
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx/access.log:/var/log/nginx/access.log
      - ./log/nginx/error.log:/var/log/nginx/error.log
    networks: 
      - gonet

secrets:
  pg-secret:
    file: db/pg-secret
